services:
  - type: web
    name: ai-code-learning-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
