services:
  - type: web
    name: ai-code-learning-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_app.py
    envVars:
  - key: OPENAI_API_KEY
    sync: false

